version: '3'

services:


  wordpress: 
    image: wordpress:latest
    container_name: wordpress 
    restart: always
    depends_on:
      - mysql
    stdin_open: true
    tty: true
    volumes:
      - ./src:/var/www/html
    ports:
      - 8005:80
    env_file:
      - .env
  
  mysql: 
    container_name: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3308:3306
    image: mysql:5.6
    restart: always
    env_file:
      - .env


  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root


  # nginx:
